### ISSUE TITLE
Доступ для разработчиков YCLIENTS

### ISSUE THREAD

**Issue by petroff** [slowprog/yclients-api#3]
@slowprog  Сможете добавить наших ребят к управлению репозиторием?

**Comment by slowprog** [comment]
Безусловно. Назовите логины кого добавить?

**Comment by petroff** [comment]
inrainbowss 
dshestakov
petroff
adrian-yc
amoseev
Nexus2116
automation-stack

**Comment by petroff** [comment]
Еще сейчас один пулл висит от кого-то

**Comment by slowprog** [comment]
Готовый

**Comment by petroff** [comment]
Спасибо!
Еще mr-yoyo, если можно

**Comment by slowprog** [comment]
Нужно!
