### ISSUE TITLE
Почему final и private?

### ISSUE THREAD

**Issue by mrTimofey** [slowprog/yclients-api#7]
- Класс YclientsApi объявлен как final. Если я хочу его расширить, то вынужден или делать что-то типа прокси-класса с доп. методами, или тупо копировать в другой класс и изменять под себя. Есть ли какой-то конкретный смысл в защите класса от наследования или может всё-таки стоит убрать final?
- Методы request, requestCurl объявлены как private. Вытекает из предыдущего вопроса. Вполне рабочая ситуация, когда, например, нужно переопределить эти методы, чтобы изменить способ отправки запросов, добавить логирование и т.д. и т.п.
- Поле $tokenPartner тоже объявлено как private, и в классе нет доступа к его значению. Опять же, непонятно, почему так сделано, и в чём смысл закрывать возможность получения токена извне.

Если можно всё это поправить, то готов сделать PR.

**Comment by petroff** [comment]
Тимофей, да конечно. Это Open Source - делайте PR

**Comment by mrTimofey** [comment]
#8 
Ну, мало ли, может вы сделали именно так с какой-то целью, которая просто мне непонятна :)

**Comment by petroff** [comment]
Ждем, что скажет @slowprog

**Comment by slowprog** [comment]
@mrTimofey Это было давно, и в тот момент либа набрасывалась для себя, а потому private, final и др. были оправданы. Но да, в реалиях общей либы лучше так не делать. Спасибо за PR.
